### PR TITLE
Genitialia Corrections and Dialogue Fixes

### PR DESCRIPTION
**Pull request by Demon-Seed**
To the first time excretion event. First time doing ever doing anything like this.

### CODE REVIEW

**Comment by Demon-Seed** [comment]
"First time doing ever doing anything like this." 
If you couldn't already tell by the funky commits lol. 1st and 2nd are duplicates and I have no idea how I did the third one.

**Comment by Demon-Seed** [comment]
Before I go mucking about. I assume translating stuff in the menu's would fuckup events unless thorough correct?

**Review by dazedanon — APPROVED** [review]
LGTM!

**Comment by dazedanon** [comment]
> Before I go mucking about. I assume translating stuff in the menu's would fuckup events unless thorough correct?


As long as you don't remove any script or vars you should be good. I'd just test just in case.

**Comment by Demon-Seed** [comment]
> > Before I go mucking about. I assume translating stuff in the menu's would fuckup events unless thorough correct?
> 
> As long as you don't remove any script or vars you should be good. I'd just test just in case.

Testing the quests seems like a right pain in the ass unless you know your way around RPGmaker. I looked at one of the names in the sexual history list aswell but the names popped up in system and I was like nope l aint riskin fucking up something looking for the japanese name but not finding anything. I did attempt to translate the "次の目的" or "Next Objective" but for whatever reason despite changing it, it would not reflect ingame. Checked to see if it was an image and I don't think it is.

I'll stick to random dialogue till I get bored enough to mess around further lol.

**Pull request merged**
